#!/bin/sh -e

vcs "-q" "-nc" "-debug_all" "-executable" "delay" "WORK.func_tb" "-lca" "-makedepends=Makefile.VCSMX_FOR_DVE_REBUILD"
gmake -f Makefile.VCSMX_FOR_DVE_REBUILD
vcs "-q" "-nc" "-debug_all" "-executable" "delay" "WORK.func_tb"
